[package]
name = "lc-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
[dependencies]
lc-engine = { path = "../lc-engine" }
lc-store = { path = "../lc-store" }
tokio.workspace = true
serde_json.workspace = true

[dev-dependencies]
lc-testkit = { path = "../lc-testkit" }
